### ISSUE TITLE
User Recipe To Cook DOM

### ISSUE THREAD

**Issue by npdarrington** [npdarrington/Whats-Cookin#15] opened 2020-09-04 23:09 UTC
As a user, I want to be able to see on my recipe card a recipe that I want to cook for this week.

- [ ] Create a place on the recipe card that will show a user (graphic or tag?) that they have selected this recipe card to cook for the week.

**Comment by hannakim91** [comment] 2020-09-15 01:53
User.recipeToCook is duplicate of User.MyFavorites

**Closed as completed** 2020-09-15 01:53 UTC
Labels: wontfix
